channel_sources:
  - conda-forge/label/rust_dev,conda-forge
channel_targets:
  - conda-forge main
rust_compiler_version:
  - 1.81.0
c_compiler:
  - clang  # [win]
c_compiler_version:
  - 17  # [win]
  - 18  # [osx]
cxx_compiler:
  - clangxx  # [win]
cxx_compiler_version:
  - 17  # [win]
c_stdlib:
- macosx_deployment_target # [osx]
c_stdlib_version:
- '13.3' # [osx]
  
polars_variant:
  - polars
  - polars-lts-cpu
  - polars-u64-idx
